global:
  values:
  workflows:
    - pr.yml

scoped:
  - name: my-app
    values:
      package: 'my-app'
      prod_url: 'https://prod.darioblanco.com'
      qa_url: 'https://qa.darioblanco.com'
      stage_url: 'https://stage.darioblanco.com'
    workflows:
      - deployment-trigger.yml
