global:
  values:
  workflows:
    - deployment.yml
    - docs.yml
    - pr.yml
    - release-draft.yml
    - workflow-creator.yml

scoped:
  - name: my-app
    values:
      package: 'example'
      prod_url: 'https://prod.darioblanco.com'
      qa_url: 'https://qa.darioblanco.com'
      stage_url: 'https://stage.darioblanco.com'
    workflows:
      - check.yml
      - deployment-trigger.yml
